# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BoucingBallUI.ui'
#
# Created: Wed Apr 03 12:01:07 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BouncingBall(object):
    def setupUi(self, BouncingBall):
        BouncingBall.setObjectName(_fromUtf8("BouncingBall"))
        BouncingBall.setEnabled(True)
        BouncingBall.resize(600, 550)
        BouncingBall.setMinimumSize(QtCore.QSize(600, 550))
        BouncingBall.setMaximumSize(QtCore.QSize(600, 550))
        self.frame = QtGui.QFrame(BouncingBall)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(20, 360, 561, 161))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.globalSpeedSlider = QtGui.QSlider(self.frame)
        self.globalSpeedSlider.setEnabled(True)
        self.globalSpeedSlider.setGeometry(QtCore.QRect(330, 20, 211, 19))
        self.globalSpeedSlider.setMinimum(1)
        self.globalSpeedSlider.setMaximum(1000)
        self.globalSpeedSlider.setProperty("value", 500)
        self.globalSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.globalSpeedSlider.setObjectName(_fromUtf8("globalSpeedSlider"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(260, 20, 61, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.nbSlider = QtGui.QSlider(self.frame)
        self.nbSlider.setEnabled(True)
        self.nbSlider.setGeometry(QtCore.QRect(60, 20, 160, 19))
        self.nbSlider.setMinimum(1)
        self.nbSlider.setMaximum(10)
        self.nbSlider.setSliderPosition(3)
        self.nbSlider.setOrientation(QtCore.Qt.Horizontal)
        self.nbSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.nbSlider.setTickInterval(1)
        self.nbSlider.setObjectName(_fromUtf8("nbSlider"))
        self.pressureBar = QtGui.QProgressBar(self.frame)
        self.pressureBar.setEnabled(True)
        self.pressureBar.setGeometry(QtCore.QRect(80, 70, 161, 23))
        self.pressureBar.setProperty("value", 24)
        self.pressureBar.setInvertedAppearance(False)
        self.pressureBar.setObjectName(_fromUtf8("pressureBar"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pauseButton = QtGui.QPushButton(self.frame)
        self.pauseButton.setEnabled(True)
        self.pauseButton.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.resetButton = QtGui.QPushButton(self.frame)
        self.resetButton.setEnabled(True)
        self.resetButton.setGeometry(QtCore.QRect(450, 50, 75, 23))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.stopBox = QtGui.QCheckBox(self.frame)
        self.stopBox.setEnabled(True)
        self.stopBox.setGeometry(QtCore.QRect(450, 110, 131, 17))
        self.stopBox.setObjectName(_fromUtf8("stopBox"))
        self.collisionNumber = QtGui.QLCDNumber(self.frame)
        self.collisionNumber.setEnabled(True)
        self.collisionNumber.setGeometry(QtCore.QRect(140, 100, 71, 23))
        self.collisionNumber.setObjectName(_fromUtf8("collisionNumber"))
        self.wallCollisionNumber = QtGui.QLCDNumber(self.frame)
        self.wallCollisionNumber.setEnabled(True)
        self.wallCollisionNumber.setGeometry(QtCore.QRect(140, 130, 71, 23))
        self.wallCollisionNumber.setObjectName(_fromUtf8("wallCollisionNumber"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(10, 135, 91, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.SoundBox = QtGui.QCheckBox(self.frame)
        self.SoundBox.setEnabled(True)
        self.SoundBox.setGeometry(QtCore.QRect(320, 90, 81, 17))
        self.SoundBox.setChecked(False)
        self.SoundBox.setObjectName(_fromUtf8("SoundBox"))
        self.allowCollisionBox = QtGui.QCheckBox(self.frame)
        self.allowCollisionBox.setEnabled(True)
        self.allowCollisionBox.setGeometry(QtCore.QRect(450, 90, 131, 17))
        self.allowCollisionBox.setChecked(True)
        self.allowCollisionBox.setObjectName(_fromUtf8("allowCollisionBox"))
        self.backgroundSoundBox = QtGui.QCheckBox(self.frame)
        self.backgroundSoundBox.setEnabled(True)
        self.backgroundSoundBox.setGeometry(QtCore.QRect(320, 110, 111, 17))
        self.backgroundSoundBox.setChecked(False)
        self.backgroundSoundBox.setObjectName(_fromUtf8("backgroundSoundBox"))
        self.bouncingFrame = QtGui.QFrame(BouncingBall)
        self.bouncingFrame.setEnabled(True)
        self.bouncingFrame.setGeometry(QtCore.QRect(20, 20, 561, 331))
        self.bouncingFrame.setAutoFillBackground(False)
        self.bouncingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bouncingFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.bouncingFrame.setObjectName(_fromUtf8("bouncingFrame"))

        self.retranslateUi(BouncingBall)
        QtCore.QMetaObject.connectSlotsByName(BouncingBall)

    def retranslateUi(self, BouncingBall):
        BouncingBall.setWindowTitle(QtGui.QApplication.translate("BouncingBall", "Bouncing Balls", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BouncingBall", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BouncingBall", "Hits/sec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BouncingBall", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseButton.setText(QtGui.QApplication.translate("BouncingBall", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("BouncingBall", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBox.setText(QtGui.QApplication.translate("BouncingBall", "Stop at Collision", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BouncingBall", "Number of wall hit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("BouncingBall", "Number of colisions", None, QtGui.QApplication.UnicodeUTF8))
        self.SoundBox.setText(QtGui.QApplication.translate("BouncingBall", "Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.allowCollisionBox.setText(QtGui.QApplication.translate("BouncingBall", "Allow Collision", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundSoundBox.setText(QtGui.QApplication.translate("BouncingBall", "Background Sound", None, QtGui.QApplication.UnicodeUTF8))

